# Generated by Django 5.1.1 on 2024-09-12 15:31

import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=1, upload_to=doctors.models.custom_upload_to, verbose_name='Imágen del doctor'),
            preserve_default=False,
        ),
    ]
